on:
  push:
    branches: [ main ]

jobs:
  run-npm-build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and Run tests
        run: |
          npm install
          npm test
        env:
          CI: true

  release-to-npm:
    runs-on: ubuntu-latest
    needs: run-npm-build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Release to npm
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
